global:
  scrape_interval: 30s
  scrape_timeout: 10s
  
rule_files:
  - blackbox-exporter.yml
  - mysqld-exporter.yml
  - node-exporter.yml
  - nginx-exporter.yml

scrape_configs:
  - job_name: node_exporter
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
    static_configs:
      - targets:
        - '192.168.0.200:9100' #node
  - job_name: nginx
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
    static_configs:
      - targets:
        - '192.168.0.200:9113' #nginx
  - job_name: mysql
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
    static_configs:
      - targets:
        - '192.168.0.200:9104' #mysql
  - job_name: blackbox
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
    static_configs:
      - targets:
        - '192.168.0.200:9115' #blackbox
  - job_name: blackbox-wordpress 
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
    params:
      module: [http_2xx]
      target: [127.0.0.1]
    static_configs:
      - targets:
        - '192.168.0.200:9115'
